/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "main.h"

// Function Declarations

void taskHandler1(void);
void taskHandler2(void);
void taskHandler3(void);
void taskHandler4(void);
void initializeSystickTimer(uint32_t tick_hz);
__attribute__((naked)) void initializeSchedulerStack(uint32_t schedulerStackStart);
void initializeTaskStack(void);
void initializeTaskHandlers(void);
__attribute__((naked)) void swicth_sp_to_psp(void);
void enable_processor_faults(void);
uint32_t get_current_task_psp(void);
void save_current_psp_value(uint32_t current_psp_value);
void update_next_task(void);

// Global Variables

uint32_t psp_of_tasks[MAX_TASK] = {
		TASK1_STACK_START,
		TASK2_STACK_START,
		TASK3_STACK_START,
		TASK4_STACK_START
};
uint32_t task_handlers[MAX_TASK];
uint32_t current_task = 0; // Initial Task 1

// Task Handlers

void taskHandler1(void){
	for(;;);
}
void taskHandler2(void){
	for(;;);
}
void taskHandler3(void){
	for(;;);
}
void taskHandler4(void){
	for(;;);
}

void initializeSystickTimer(uint32_t tick_hz){
	uint32_t *pSYST_RVR = (uint32_t*)0xE000E014; // SysTick Reload Value Register Address
	uint32_t *pSYST_CSR = (uint32_t*)0xE000E010; // SysTick Control and Status Register Address
	uint32_t count_value = (SYSTICK_TIMER_CLOCK/tick_hz)-1; // Count Value for 1ms (16Mhz/1KHz = 16000)

	// Clear SYST_RVR
	*pSYST_RVR &= ~(0x00FFFFFF); // [31:24] - reserved, [23:0] - RELOAD

	// Load Count Value to SYST_RVR
	*pSYST_RVR |= count_value; // N-1

	// SYST_CSR Settings
	*pSYST_CSR |= (1 << 1); // Enables SysTick exception - SYST_CSR[1]
	*pSYST_CSR |= (1 << 2); // Indicates the processor clock source - SYST_CSR[2]

	// Enables the counter - SYST_CSR[0]
	*pSYST_CSR |= (1 << 0);
}

// Scheduler Stack Initialization
__attribute__((naked)) void initializeSchedulerStack(uint32_t schedulerStackStart){

	__asm volatile("MSR MSP,%0"::"r"(schedulerStackStart):); // MSP = schedulerStackStart
	__asm volatile("BX LR"); // return to main function
}

// Task Stack Initialization
void initializeTaskStack(void){

	uint32_t *pPSP;

	for(int i=0;i<MAX_TASK;i++){
		pPSP = (uint32_t*)psp_of_tasks[i]; // Start Address of each task

		// XPSR Initialization
		pPSP--;
		*pPSP = INITIAL_XPSR; // 0x00100000 (Set T-bit = 1)

		// PC Initialization
		pPSP--;
		*pPSP = task_handlers[i] | 1U; // Initial Task Handler Address

		// LR Initialization
		pPSP--;
		*pPSP = EXC_RETURN; // Return to Thread Mode with PSP

		// Reset the 13 General Purpose Registers(R0 to R12)
		for(int j=0;j<13;j++){
			pPSP--;
			*pPSP = 0;
		}

		psp_of_tasks[i] = (uint32_t)pPSP; // Preserve that PSP Value
	}

}

// Initialize Task Handlers Function Address
void initializeTaskHandlers(void){
	task_handlers[0] = (uint32_t)taskHandler1;
	task_handlers[1] = (uint32_t)taskHandler2;
	task_handlers[2] = (uint32_t)taskHandler3;
	task_handlers[3] = (uint32_t)taskHandler4;
}

uint32_t get_current_task_psp(void){
	return psp_of_tasks[current_task];
}

__attribute__((naked)) void swicth_sp_to_psp(void){

	// Initialize PSP with Task 1 Stack Start Address
	__asm volatile("PUSH {LR}"); // preserve LR to return back to main
	__asm volatile("BL get_current_task_psp"); // PC = currrent_task_psp and Stack of current task stored in R0
	__asm volatile("MSR PSP,R0"); // Copy the Stack from R0 to PSP
	__asm volatile("POP {LR}"); // Pop LR to return back from get_current_task_psp

	// Change SP to PSP using CONTROL Register
	__asm volatile("MOV R0,#0x02"); // Immediate Value to SET CONTROl[1] = SPSEL = 1 -> PSP
	__asm volatile("MSR CONTROL,R0");

	__asm volatile("BX LR"); // return back to main

}

void enable_processor_faults(void){

	uint32_t *pSHCSR = (uint32_t *)0xE000ED24; // System Handler Control Status Register

	*pSHCSR |= (1 << 16); // SHCSR[16] - MemManage Fault Pending Status Enable
	*pSHCSR |= (1 << 17); // SHCSR[17] - Bus Fault Pending Status Enable
	*pSHCSR |= (1 << 18); // SHCSR[18] - usage Fault Pending Status Enable
}

// Exception Handlers

// HardFault Handler
void HardFault_Handler(void){
	for(;;);
}

// MemManageFault Handler
void MemManage_Handler(void){
	for(;;);
}

// BusFault Handler
void BusFault_Handler(void){
	for(;;);
}

// UsageFault Handler
void UsageFault_Handler(void){
	for(;;);
}

// Save Current PSP Value
void save_current_psp_value(uint32_t current_psp_value){
	psp_of_tasks[current_task] = current_psp_value;
}

// Update Next task in Round Robin Fashion
void update_next_task(void){
	current_task++;
	current_task %= MAX_TASK;
}

// SysTic Handler - Scheduler
__attribute__((naked)) void SysTick_Handler(void){

	/* Save the Context of Current task */

	// Stack Frame 1 - {XPSR, PC, LR, R12, R3, R2, R1, R0} automatically pushed to stack by processor

	// Get the Current Task PSP
	__asm volatile("MRS R0,PSP");

	// Using that PSP value store Stack Frame 2 - {R4 to R11}
	// Store R4 to R11 in the Memory by Decrementing the PSP with store updated PPS in RO after every STORE
	__asm volatile("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}"); // preserve LR to return back to SysTic handler

	// Save Current PSP Value
	__asm volatile("BL save_current_psp_value"); // PC = save_current_psp_value with Argument as R0

	/* Retrieve the Context of Next Task*/

	// Decide next task to run
	__asm volatile("BL update_next_task"); // PC = upadte_next_task

	// Get its past PSP value
	__asm volatile("BL get_current_task_psp"); // R0 = Current Task PSP Value

	// Using that PSP value retrieve Stack Frame - 2(R4 to R11)
	// Load the Data from Memory Increment and store from R4 to R11 and store updated Address in R0 after every LOAD
	__asm volatile("LDMIA R0!,{R4-R11}");

	// Update Current task PSP
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}"); // Pop LR to return back from get_current_task_psp

	__asm volatile("BX LR"); // PC = Next PSP value
}

int main(void){
	//enable_processor_faults();
	initializeSchedulerStack(SCHEDULER_STACK_START);
	initializeTaskHandlers();
	initializeTaskStack();
	initializeSystickTimer(TICK_HZ);
	swicth_sp_to_psp();
	taskHandler1();
	for(;;);
}
